elasticsearch-cn/elasticsearch-definitive-guide

100_Full_Text_Search/10_Multi_word_queries.asciidoc

chapter13_part3: /100_Full_Text_Search/10_Multi_word_queries.asciidoc

---

020_Distributed_Cluster/00_Intro.asciidoc

020_Distributed_Cluster/00_Intro.asciidoc 翻译

---

020_Distributed_Cluster/00_Intro.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#72

Revert "020_Distributed_Cluster/00_Intro.asciidoc 翻译"

---

170_Relevance/65_Script_score.asciidoc

chapter17_part13: /170_Relevance/65_Script_score.asciidoc

---

270_Fuzzy_matching/60_Phonetic_matching.asciidoc

chapter24_part6: /270_Fuzzy_matching/60_Phonetic_matching.asciidoc

---

270_Fuzzy_matching/50_Scoring_fuzziness.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#143

Revert "chapter24_part5: /270_Fuzzy_matching/50_Scoring_fuzziness.asciidoc"

---

056_Sorting/88_String_sorting.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#140

Revert "chapter8_part2: /056_Sorting/88_String_sorting.asciidoc"

---

060_Distributed_Search/00_Intro.asciidoc
060_Distributed_Search/05_Query_phase.asciidoc

Revert "060 distributed search/00_Intro.asciidoc and 05_Query_phase.asciidoc"

---

070_Index_Mgmt/10_Settings.asciidoc
130_Partial_Matching/05_Postcodes.asciidoc
510_Deployment/45_dont_touch.asciidoc

Fix Chinese filename

---

054_Query_DSL/80_Validating_queries.asciidoc

第一次提交80_Validating_queries.asciidoc翻译

chapter7_part6:/054_Query_DSL/80_Validating_queries.asciidoc

---

070_Index_Mgmt/30_Root_Object.asciidoc

chapter10_part6:/070_Index_Mgmt/30_Root_Object.asciidoc

---

054_Query_DSL/65_Queries_vs_filters.asciidoc

提交65_Queries_vs_filters.asciidoc 翻译

chapter7_part3: /054_Query_DSL/65_Queries_vs_filters.asciidoc

---

070_Index_Mgmt/15_Configure_Analyzer.asciidoc

chapter10_part3: /070_Index_Mgmt/15_Configure_Analyzer.asciidoc

---

510_Deployment/50_heap.asciidoc

chapter46_part6: /510_Deployment/50_heap.asciidoc

---

400_Relationships/25_Concurrency.asciidoc

chapter41_part5: /400_Relationships/25_Concurrency.asciidoc

---

510_Deployment/30_other.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#135
编译失败

Revert "chapter46_part3: /510_Deployment/30_other.asciidoc"

---

510_Deployment/30_other.asciidoc

chapter46_part3: /510_Deployment/30_other.asciidoc

---

240_Stopwords/20_Using_stopwords.asciidoc

chapter240_part20:240_Stopwords/20_Using_stopwords.asciidoc

---

130_Partial_Matching/20_Match_phrase_prefix.asciidoc

chapter16_part5: /130_Partial_Matching/20_Match_phrase_prefix.asciidoc

---

110_Multi_Field_Search/20_Tuning_best_field_queries.asciidoc

chapter14_part4: /110_Multi_Field_Search/20_Tuning_best_field_queries.asciidoc

---

070_Index_Mgmt/05_Create_Delete.asciidoc

chapter/chapter10_part1: /070_Index_Mgmt/05_Create_Delete.asciidoc

---

130_Partial_Matching/25_Index_time.asciidoc

chapter16_part6: /130_Partial_Matching/25_Index_time.asciidoc

---

130_Partial_Matching/40_Compound_words.asciidoc

chapter16_part9: /130_Partial_Matching/40_Compound_words.asciidoc

---

110_Multi_Field_Search/10_Single_query_string.asciidoc

chapter14_part3: /110_Multi_Field_Search/10_Single_query_string.asciidoc

---

01_Search_in_depth.asciidoc

1. score=》评分？
2. score和longtail的格式丢了
3. 结尾少了一个 『。』
4. language awareness=语言感知？

p2_preface: /01_Search_in_depth.asciidoc #improve 1

---

402_Nested/31_Nested_mapping.asciidoc

chapter42_part2:/402_Nested/31_Nested_mapping.asciidoc

---

110_Multi_Field_Search/05_Multiple_query_strings.asciidoc

chapter14_part2: /110_Multi_Field_Search/05_Multiple_query_strings.asciidoc #Fix

---

402_Nested/35_Nested_aggs.asciidoc

chapter42_part5:/402_Nested/35_Nested_aggs.asciidoc

---

110_Multi_Field_Search/55_Not_analyzed.asciidoc

chapter14_part11: /110_Multi_Field_Search/55_Not_analyzed.asciidoc

---

130_Partial_Matching/35_Search_as_you_type.asciidoc

chapter16_part8: /130_Partial_Matching/35_Search_as_you_type.asciidoc #Fix

---

book-docinfo.xml
book.asciidoc
page_header.html
titlepage.html

misc translation

---

170_Relevance/75_Changing_similarities.asciidoc

chapter17_part15: /170_Relevance/75_Changing_similarities.asciidoc

---

070_Index_Mgmt/05_Create_Delete.asciidoc

/070_Index_Mgmt/05_Create_Delete.asciidoc

Fix filename in _deleting_an_index.html

---

110_Multi_Field_Search/25_Multi_match_query.asciidoc

chapter14_part5: /110_Multi_Field_Search/25_Multi_match_query.asciidoc

---

270_Fuzzy_matching/10_Intro.asciidoc

chapter24_part1: /270_Fuzzy_matching/10_Intro.asciidoc

---

010_Intro/20_Document.asciidoc

chapter1_part20:/010_Intro/20_Document.asciidoc

---

270_Fuzzy_matching/20_Fuzziness.asciidoc

chapter24_part2: /270_Fuzzy_matching/20_Fuzziness.asciidoc

---

110_Multi_Field_Search/50_Cross_field.asciidoc

chapter14_part10: /110_Multi_Field_Search/50_Cross_field.asciidoc

---

110_Multi_Field_Search/40_Field_centric.asciidoc

chapter14_part8: /110_Multi_Field_Search/40_Field_centric.asciidoc

---

170_Relevance/25_Query_scoring.asciidoc

chapter17_part5: /170_Relevance/25_Query_scoring.asciidoc

---

260_Synonyms/60_Multi_word_synonyms.asciidoc

chapter23_part6:/260_Synonyms/60_Multi_word_synonyms.asciidoc

---

260_Synonyms/70_Symbol_synonyms.asciidoc

chapter23_part7:/260_Synonyms/70_Symbol_synonyms.asciidoc

---

020_Distributed_Cluster/35_Coping_with_failure.asciidoc

chapter2_part8:/020_Distributed_Cluster/35_Coping_with_failure.asciidoc

---

400_Relationships/22_Top_hits.asciidoc

chapter41_part4: /400_Relationships/22_Top_hits.asciidoc

---

170_Relevance/55_Random_scoring.asciidoc

chapter17_part11: /170_Relevance/55_Random_scoring.asciidoc

---

170_Relevance/15_Practical_scoring.asciidoc

chapter17_part3: /170_Relevance/15_Practical_scoring.asciidoc

---

240_Stopwords/70_Relevance.asciidoc

chapter240_part70:240_Stopwords/70_Relevance

---

010_Intro/10_Installing_ES.asciidoc

1. 给`010_Intro/10_Installing_ES.asciidoc`添加翻译；
2. Sense方面不是很懂，希望各位支持下；
3. 翻译与格式多提意见；
4. @xuej @medcl

chapter1_part1: /010_Intro/10_Installing_ES.asciidoc

---

054_Query_DSL/55_Request_body_search.asciidoc

chapter7_part1:/054_Query_DSL/55_Request_body_search.asciidoc

---

300_Aggregations/35_date_histogram.asciidoc

原来的提交 pr 的同学 @weikuo0506 一直没有修改 review 的建议，
close https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/197  
这个 pr review 了一遍   @weikuo0506  @fanyer  @medcl @node

chapter22_part6_x:/300_Aggregations/35_date_histogram.asciidoc

---

200_Language_intro/00_Intro.asciidoc

chapter18_part0: /200_Language_intro/00_intro.asciidoc

---

300_Aggregations/95_analyzed_vs_not.asciidoc

chapter22_part17: /300_Aggregations/95_analyzed_vs_not.asciidoc

---

056_Sorting/90_What_is_relevance.asciidoc

原 pr close https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/199

chapter8_part3_x:/056_Sorting/90_What_is_relevance.asciidoc

---

056_Sorting/88_String_sorting.asciidoc

原 pr  close https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/200

chapter8_part2_x:/056_Sorting/88_String_sorting.asciidoc

---

200_Language_intro/20_Configuring.asciidoc

chapter18_part2: /200_Language_intro/20_Configuring.asciidoc

---

07_Admin.asciidoc

重提 pr.
close https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/21
open https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/385

chapterP7_part1_x:/07_Admin.asciidoc

---

080_Structured_Search/40_bitsets.asciidoc

chapter12_part8: /080_Structured_Search/40_bitsets.asciidoc #Fix

---

170_Relevance/45_Popularity.asciidoc

chapter17_part9: /170_Relevance/45_Popularity.asciidoc #Fix

---

110_Multi_Field_Search/45_Custom_all.asciidoc

chapter14_part9: /110_Multi_Field_Search/45_Custom_all.asciidoc #Fix

---

100_Full_Text_Search/30_Controlling_analysis.asciidoc

chapter13_part7: /100_Full_Text_Search/30_Controlling_analysis.asciidoc #Fix

---

300_Aggregations/75_sigterms.asciidoc

chapter22_part14:/300_Aggregations/75_sigterms.asciidoc

---

404_Parent_Child/70_Practical_considerations.asciidoc

chapter43_part7:/404_Parent_Child/70_Practical_considerations.asciidoc

---

300_Aggregations/23_extra_metrics.asciidoc

chapter22_part4:/300_Aggregations/23_extra_metrics.asciidoc

---

00_Getting_started.asciidoc

chapter0_part1: 00_Getting_started.asciidoc

---

010_Intro/15_API.asciidoc

chapter010_part15:/010_Intro/15_API.asciidoc

---

240_Stopwords/60_Common_grams.asciidoc

chapter240_part60:240_Stopwords/60_Common_grams

---

260_Synonyms/40_Expand_contract.asciidoc

chapter23_part4:/260_Synonyms/40_Expand_contract.asciidoc

chapter23_part4:/260_Synonyms/40_Expand_contract.asciidoc

---

260_Synonyms/20_Using_synonyms.asciidoc

chapter23_part2:/260_Synonyms/20_Using_synonyms.asciidoc

---

170_Relevance/30_Not_quite_not.asciidoc

chapter17_part6: /170_Relevance/30_Not_quite_not.asciidoc

---

260_Synonyms/30_Synonym_formats.asciidoc

chapter23_part3:/260_Synonyms/30_Synonym_formats.asciidoc
