elasticsearch-cn/elasticsearch-definitive-guide

510_Deployment/50_heap.asciidoc

之前的 50_heap.asciidoc 已被 merged ，重提 pr 修改 cluster 的翻译笔误，“群集”修改为“集群”。
@medcl @chenryn @sdlyjzh 🙏

chapter46_part6: /510_Deployment/50_heap.asciidoc

---

080_Structured_Search/10_compoundfilters.asciidoc

chapter12_part3: /080_Structured_Search/10_compoundfilters.asciidoc
第二部分：第12章，结构化搜索，组合过滤器

chapter12_part3: /080_Structured_Search/10_compoundfilters.asciidoc

---

100_Full_Text_Search/15_Combining_queries.asciidoc

chapter13_part4: /100_Full_Text_Search/15_Combining_queries.asciidoc

---

270_Fuzzy_matching/50_Scoring_fuzziness.asciidoc

chapter24_part5: /270_Fuzzy_matching/50_Scoring_fuzziness.asciidoc

---

270_Fuzzy_matching/60_Phonetic_matching.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#144

Revert "chapter24_part6: /270_Fuzzy_matching/60_Phonetic_matching.asciidoc"

---

056_Sorting/95_Fielddata.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#141

Revert "chapter8_part4: /056_Sorting/95_Fielddata.asciidoc"

---

056_Sorting/88_String_sorting.asciidoc

Sorting use old tag
`fielddata-intro` was moved to `aggregations-and-analysis`

Fix document building error

---

270_Fuzzy_matching/40_Fuzzy_match_query.asciidoc

chapter24_part4: /270_Fuzzy_matching/40_Fuzzy_match_query.asciidoc

---

400_Relationships/20_Denormalization.asciidoc

chapter41_part3: /400_Relationships/20_Denormalization.asciidoc

---

130_Partial_Matching/05_Postcodes.asciidoc

chapter16_part2: /130_Partial_Matching/05_Postcodes.asciidoc

---

060_Distributed_Search/00_Intro.asciidoc
060_Distributed_Search/05_Query_phase.asciidoc

060 distributed search/00_Intro.asciidoc and 05_Query_phase.asciidoc

---

060_Distributed_Search/00_Intro.asciidoc

chapter9_part1: /060_Distributed_Search/00_Intro.asciidoc

---

060_Distributed_Search/00_Intro.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#255

Revert "chapter9_part1: /060_Distributed_Search/00_Intro.asciidoc"

---

070_Index_Mgmt/10_Settings.asciidoc

chapter10_part2:/070_Index_Mgmt/10_Settings.asciidoc

---

070_Index_Mgmt/45_Default_Mapping.asciidoc

chapter10_part12:/070_Index_Mgmt/45_Default_Mapping.asciidoc

---

520_Post_Deployment/30_indexing_perf.asciidoc

这里讨论点翻译以外的事情。`index.translog.flush_threshold_size`这个设置，我感觉书里写的不太对啊……ES的segment生成是由indexing buffer大小以及更重要的refresh_interval决定的，加大translog的size，并不能导致larger segment啊。我理解加大translog的flush其实对写入没多大影响，translog这种顺序IO，能花多大事。

chapter47_part3:/520_Post_Deployment/30_indexing_perf.asciidoc

---

404_Parent_Child/55_Has_parent.asciidoc

chapter43_part4: /404_Parent_Child/55_Has_parent.asciidoc

---

404_Parent_Child/50_Has_child.asciidoc

chapter43_part3: /404_Parent_Child/50_Has_child.asciidoc

---

404_Parent_Child/60_Children_agg.asciidoc

chapter43_part5: /404_Parent_Child/60_Children_agg.asciidoc

---

050_Search/05_Empty_search.asciidoc
050_Search/10_Multi_index_multi_type.asciidoc
050_Search/15_Pagination.asciidoc
050_Search/20_Query_string.asciidoc

Reverts elasticsearch-cn/elasticsearch-definitive-guide#284

Revert "chapter05_part2:/050_Search/10_Multi_index_multi_type.asciidoc"

---

100_Full_Text_Search/20_How_match_uses_bool.asciidoc

chapter13_part5: /100_Full_Text_Search/20_How_match_uses_bool.asciidoc

---

110_Multi_Field_Search/15_Best_field.asciidoc

chapter14_part4: /110_Multi_Field_Search/15_Best_field.asciidoc
